version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/repo
    steps:
      - checkout
      # node_modules以下はファイルが多いのでキャッシュを使って高速化
      # package.jsonに変更があったときはキャッシュを使わない
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      # zipコマンドをインストール
      - run:
          name: install zip
          command: "sudo apt-get update && sudo apt-get install -y zip"
      # アプリをlambda用にzipにする
      - run:
          name: archive app
          command: "zip -r package.zip index.js node_modules"
      # 後続のデプロイジョブで使えるようにpackage.zipを永続化しておく
      - persist_to_workspace:
          root: .
          paths:
            - package.zip
  # deployはawscliを使う
  # 環境変数としてAWS_ACCESS_KEY_IDとAWS_SECRET_ACCESS_KEYを設定しておく必要がある
  # circleciのリポジトリごとの設定からEnvironment Variables -> Add Variable
  deploy:
    docker:
      - image: circleci/python:2.7-jessie
    steps:
      - attach_workspace:
          at: .
      - run:
          name: install awscli
          command: sudo pip install awscli
      - run:
          name: deploy to lambda
          command: >
            aws lambda update-function-code
            --function-name cicleci_test
            --region ap-northeast-1
            --zip-file fileb://package.zip
            --publish

# ビルドとデプロイをワークフローとして定義
# ビルド後にデプロイが実行されるように
workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master